spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/intermark
    username: root
    password: intermark123!

  jpa:
    properties:
      hibernate:
        show-sql: true
        format_sql: true
    hibernate:
      ddl-auto: create

logging:
  level:
    org.springframework: debug
    org.hibernate.SQL: debug
    org.hibernate.type: trace