name: cd

on: # 이벤트 트리거
  push:
    branches: [ "develop", "ADD/#126" ]

jobs:
  docker-build-and-push-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      -
        name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      -
        name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      -
        name: setup Gradle permission
        run: chmod +x gradlew
      -
        name: make bootJar
        run: ./gradlew bootJar
      -
        name: login to ghcr
        uses: docker/login-actions@v2
        with:
          registry: ghcr.io
          username: ${{secrets.GHCR_USERNAME}}
          password: ${{secrets.GHCR_TOKEN}}
      -
        name: Build Docker Image
        run: |
          IMAGE_NAME=${{secrets.DOCKER_REPO}}
          IMAGE_TAG=$(git describe --tags)
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
      -
        name: Push Docker Image
        run: |
          IMAGE_NAME=${{secrets.DOCKER_REPO}}
          IMAGE_TAG=$(git describe --tags)
          docker push $IMAGE_NAME:$IMAGE_TAG
          docker push $IMAGE_NAME:latest
      -
        name: move docker-compose to ec2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{secrets.SSH_KEY}}
          port: ${{ secrets.PORT }}
          source: "docker-compose.yml"
          target: "intermark"
      -
        name: deploy to ec2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.SSH_KEY}}
          script: |
            cd ./intermark
            mkdir ./env & ${{secrets.SPRING_ENV}} > ./env/spring.env & ${{secrets.DB_ENV}} > ./env/db.env
            docker-compose stop
            docker-compose rm ${{secrets.SERVICES_EXCEPT_DB}}
            docker-compose up -d
                      
        

